apiVersion: v1
kind: PersistentVolume
metadata:
  name: cka-pv-q3
  labels:
    type: local
spec:
  storageClassName: cka-manual-mapping
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/app/data
