apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cka-pvc-q3
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: cka-manual-mapping
