apiVersion: v1
kind: LimitRange
metadata:
  name: cka-limitrange-container
  namespace: default
spec:
  limits:
    - default:
        cpu: 300m
        memory: 250M
      defaultRequest:
        cpu: 200m
        memory: 250M
      max:
        cpu: 1
        memory: 1G
      min:
        cpu: 200m
        memory: 100M
      type: Container
