apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: pv-ns
  name: pod-viewer-rb
subjects:
  - name: default
    kind: ServiceAccount
    namespace: pv-ns
roleRef:
  name: pod-viewer-role
  kind: Role
  apiGroup: rbac.authorization.k8s.io
