apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-cluster-rb
subjects:
  - name: default
    kind: ServiceAccount
    namespace: pv-ns
roleRef:
  name: pod-cluster-role
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
