apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cka-hpa-deployment
  namespace: default
spec:
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 25
          type: Utilization
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cka-hpa-deployment
