apiVersion: apps/v1
kind: Deployment
metadata:
  name: cka-hpa-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      run: cka-hpa-deployment
  replicas: 2
  template:
    metadata:
      labels:
        run: cka-hpa-deployment
    spec:
      containers:
      - name: cka-hpa-deployment
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 400m
---
apiVersion: v1
kind: Service
metadata:
  name: cka-hpa-service
  labels:
    run: cka-hpa-deployment
spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    run: cka-hpa-deployment
