apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cka-q2-sc
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
reclaimPolicy: Delete
allowVolumeExpansion: false
mountOptions:
  - debug
volumeBindingMode: WaitForFirstConsumer
