apiVersion: v1
kind: PersistentVolume
metadata:
  name: cka-pv-hostpath-walkthru
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /pv/data
