apiVersion: v1
kind: PersistentVolume
metadata:
  name: cka-pv-hostpath
spec:
  capacity:
    storage: 3Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /pv/data
