apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cka-sc-aws-gp3
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
reclaimPolicy: Retain           
volumeBindingMode: Immediate
