apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: cka-manual-mapping
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    database: mysql
spec:
  storageClassName: cka-manual-mapping
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
