apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-nginx
spec:
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 25
          type: Utilization
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-nginx
