apiVersion: apps/v1
kind: Deployment
metadata:
  name: cka-rolling
  labels:
    workload: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      workload: nginx
  template:
    metadata:
      labels:
        workload: nginx
    spec:
      containers:
        - image: nginx:1.24.0
          name: nginx
          ports:
            - containerPort: 80
